### ISSUE TITLE
这行应该是存在bug，会导致其他插件的功能触发失败

### ISSUE THREAD

**Issue by black-zero358** [zhongwen-4/nonebot-plugin-running-state#1]
https://github.com/zhongwen-4/nonebot-plugin-running-state/blob/11458a133c7f131630e641ccf50cc862be4f31ca/nonebot_plugin_running_state/__init__.py#L26

我明天试着改改代码验证一下

**Comment by zhongwen-4** [comment]
> https://github.com/zhongwen-4/nonebot-plugin-running-state/blob/11458a133c7f131630e641ccf50cc862be4f31ca/nonebot_plugin_running_state/__init__.py#L26
> 
> 我明天试着改改代码验证一下

可能是权限太高导致的()

**Comment by black-zero358** [comment]
> > https://github.com/zhongwen-4/nonebot-plugin-running-state/blob/11458a133c7f131630e641ccf50cc862be4f31ca/nonebot_plugin_running_state/__init__.py#L26
> > 
> > 我明天试着改改代码验证一下
> 
> 可能是权限太高导致的()

感觉是这样的，优先级太高
